import React, { createContext, useContext, useEffect, useMemo, useState } from 'react'
import type { AppLanguage } from '../../shared/types'
import { useAuthStore } from './store/auth.store'

type Dictionary = Record<string, string>
const translations: Record<AppLanguage, Dictionary> = {
  hr: { language: 'Jezik', croatian: 'Hrvatski', english: 'Engleski', german: 'Njemački', french: 'Francuski', servers: 'Serveri', dashboard: 'Nadzorna ploča', mods: 'Modovi', settings: 'Postavke', admin: 'Admin', logs: 'Zapisnik', panel: 'Panel', logout: 'Odjava', noServer: 'Nema servera', activeServerOverview: 'Pregled aktivnog servera', sync: 'Sinkroniziraj', syncing: 'Sinkronizacija...', checking: 'Provjera...', noServerSelected: 'Nema odabranog servera', selectServer: 'Odaberite server u kategoriji Serveri', goToServers: 'Idi na servere', online: 'Online', offline: 'Offline', unknown: 'Nepoznato', players: 'igrača', map: 'Mapa', version: 'Verzija', lastSync: 'Zadnja sinkronizacija', never: 'Nikad', myMods: 'Moji modovi', missing: 'Nedostaje', update: 'Ažuriranje', launchServer: 'Uđi na server', launching: 'Provjera i pokretanje...', loginDiscord: 'Prijava putem Discorda', loggingIn: 'Prijava u tijeku...', configureDiscord: 'Konfiguriraj Discord', loading: 'Učitavanje...', accessDenied: 'Nemate pristup launcheru', addServer: 'Dodaj server', addFirstServer: 'Dodaj prvi server', noServers: 'Nema dodanih servera', clickAddServer: 'Kliknite „Dodaj server” za konfiguraciju', launcherSettings: 'Konfiguracija launchera', save: 'Spremi', cancel: 'Odustani', close: 'Zatvori', delete: 'Obriši', edit: 'Uredi', active: 'AKTIVAN', status: 'Status', local: 'Lokalno', server: 'Server', size: 'Veličina', action: 'Akcija', clearCompleted: 'Očisti završeno', completed: 'Završeno' },
  en: { language: 'Language', croatian: 'Croatian', english: 'English', german: 'German', french: 'French', servers: 'Servers', dashboard: 'Dashboard', mods: 'Mods', settings: 'Settings', admin: 'Admin', logs: 'Logs', panel: 'Panel', logout: 'Log out', noServer: 'No server', activeServerOverview: 'Active server overview', sync: 'Synchronize', syncing: 'Synchronizing...', checking: 'Checking...', noServerSelected: 'No server selected', selectServer: 'Select a server in the Servers section', goToServers: 'Go to Servers', online: 'Online', offline: 'Offline', unknown: 'Unknown', players: 'players', map: 'Map', version: 'Version', lastSync: 'Last sync', never: 'Never', myMods: 'My mods', missing: 'Missing', update: 'Update', launchServer: 'Join server', launching: 'Checking and launching...', loginDiscord: 'Sign in with Discord', loggingIn: 'Signing in...', configureDiscord: 'Configure Discord', loading: 'Loading...', accessDenied: 'You do not have access to the launcher', addServer: 'Add server', addFirstServer: 'Add first server', noServers: 'No servers added', clickAddServer: 'Click “Add server” to configure one', launcherSettings: 'Launcher configuration', save: 'Save', cancel: 'Cancel', close: 'Close', delete: 'Delete', edit: 'Edit', active: 'ACTIVE', status: 'Status', local: 'Local', server: 'Server', size: 'Size', action: 'Action', clearCompleted: 'Clear completed', completed: 'Completed' },
  de: { language: 'Sprache', croatian: 'Kroatisch', english: 'Englisch', german: 'Deutsch', french: 'Französisch', servers: 'Server', dashboard: 'Übersicht', mods: 'Mods', settings: 'Einstellungen', admin: 'Admin', logs: 'Protokoll', panel: 'Panel', logout: 'Abmelden', noServer: 'Kein Server', activeServerOverview: 'Übersicht des aktiven Servers', sync: 'Synchronisieren', syncing: 'Synchronisierung...', checking: 'Prüfung...', noServerSelected: 'Kein Server ausgewählt', selectServer: 'Wähle einen Server im Bereich Server', goToServers: 'Zu Servern', online: 'Online', offline: 'Offline', unknown: 'Unbekannt', players: 'Spieler', map: 'Karte', version: 'Version', lastSync: 'Letzte Synchronisierung', never: 'Nie', myMods: 'Meine Mods', missing: 'Fehlt', update: 'Aktualisierung', launchServer: 'Server beitreten', launching: 'Prüfung und Start...', loginDiscord: 'Mit Discord anmelden', loggingIn: 'Anmeldung...', configureDiscord: 'Discord konfigurieren', loading: 'Wird geladen...', accessDenied: 'Du hast keinen Zugriff auf den Launcher', addServer: 'Server hinzufügen', addFirstServer: 'Ersten Server hinzufügen', noServers: 'Keine Server hinzugefügt', clickAddServer: 'Klicke auf „Server hinzufügen”, um einen zu konfigurieren', launcherSettings: 'Launcher-Konfiguration', save: 'Speichern', cancel: 'Abbrechen', close: 'Schließen', delete: 'Löschen', edit: 'Bearbeiten', active: 'AKTIV', status: 'Status', local: 'Lokal', server: 'Server', size: 'Größe', action: 'Aktion', clearCompleted: 'Abgeschlossene löschen', completed: 'Abgeschlossen' },
  fr: { language: 'Langue', croatian: 'Croate', english: 'Anglais', german: 'Allemand', french: 'Français', servers: 'Serveurs', dashboard: 'Tableau de bord', mods: 'Mods', settings: 'Paramètres', admin: 'Admin', logs: 'Journal', panel: 'Panneau', logout: 'Déconnexion', noServer: 'Aucun serveur', activeServerOverview: 'Aperçu du serveur actif', sync: 'Synchroniser', syncing: 'Synchronisation...', checking: 'Vérification...', noServerSelected: 'Aucun serveur sélectionné', selectServer: 'Sélectionnez un serveur dans la section Serveurs', goToServers: 'Aller aux serveurs', online: 'En ligne', offline: 'Hors ligne', unknown: 'Inconnu', players: 'joueurs', map: 'Carte', version: 'Version', lastSync: 'Dernière synchronisation', never: 'Jamais', myMods: 'Mes mods', missing: 'Manquant', update: 'Mise à jour', launchServer: 'Rejoindre le serveur', launching: 'Vérification et lancement...', loginDiscord: 'Connexion avec Discord', loggingIn: 'Connexion en cours...', configureDiscord: 'Configurer Discord', loading: 'Chargement...', accessDenied: 'Vous n’avez pas accès au launcher', addServer: 'Ajouter un serveur', addFirstServer: 'Ajouter le premier serveur', noServers: 'Aucun serveur ajouté', clickAddServer: 'Cliquez sur « Ajouter un serveur » pour le configurer', launcherSettings: 'Configuration du launcher', save: 'Enregistrer', cancel: 'Annuler', close: 'Fermer', delete: 'Supprimer', edit: 'Modifier', active: 'ACTIF', status: 'Statut', local: 'Local', server: 'Serveur', size: 'Taille', action: 'Action', clearCompleted: 'Effacer les éléments terminés', completed: 'Terminé' }
}

interface I18nValue { language: AppLanguage; setLanguage: (language: AppLanguage) => Promise<void>; t: (key: string) => string }
const I18nContext = createContext<I18nValue | null>(null)
export function I18nProvider({ children }: { children: React.ReactNode }): React.ReactElement {
  const user = useAuthStore((state) => state.user)
  const [language, setCurrentLanguage] = useState<AppLanguage>('hr')
  useEffect(() => { if (!user) { setCurrentLanguage('hr'); return }; window.electron.getUserLanguage(user.id).then((r) => { if (r.success && r.data) setCurrentLanguage(r.data) }).catch(() => undefined) }, [user?.id])
  const value = useMemo(() => ({ language, setLanguage: async (next: AppLanguage) => { setCurrentLanguage(next); if (user) await window.electron.saveUserLanguage(user.id, next) }, t: (key: string) => translations[language][key] ?? translations.hr[key] ?? key }), [language, user])
  return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>
}
export function useI18n(): I18nValue { const value = useContext(I18nContext); if (!value) throw new Error('useI18n must be used within I18nProvider'); return value }
export const languageOptions: { value: AppLanguage; labelKey: string; flag: string }[] = [{ value: 'hr', labelKey: 'croatian', flag: '🇭🇷' }, { value: 'en', labelKey: 'english', flag: '🇬🇧' }, { value: 'de', labelKey: 'german', flag: '🇩🇪' }, { value: 'fr', labelKey: 'french', flag: '🇫🇷' }]
